# Generated by Django 5.2.7 on 2025-12-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('DonorID', models.AutoField(primary_key=True, serialize=False)),
                ('DonorName', models.CharField(max_length=100)),
                ('UserName', models.CharField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=128)),
                ('DateOfBirth', models.DateField(blank=True, null=True)),
                ('Gender', models.CharField(max_length=10)),
                ('Profession', models.CharField(max_length=100)),
                ('BadHabits', models.TextField()),
                ('BloodGroup', models.CharField(max_length=5)),
                ('Diseases', models.CharField(blank=True, max_length=300, null=True)),
                ('HadRecentInfection', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('RecentInfections', models.CharField(blank=True, max_length=300)),
                ('Location', models.TextField()),
                ('State', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
